import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";

const outfit = Outfit({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Rado - A Simple Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={outfit.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
